[package]
name = "api-response"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.215", features = ["derive"] }
serde_json = { version = "1.0.133" }
axum = { version = "0.7.9" }